name: Unit testing

on: [push]

jobs:
  test-and-linting:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"


